[project]
name = "mp4-to-mp3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moviepy>=2.2.1",
    "pyinstaller>=6.16.0",
    "whisper>=1.1.10",
]
